"""Application configuration.

Every secret and environment-specific value comes from environment variables
(or a .env file next to the project root). Nothing sensitive is stored in the
source tree or in the database in plain text.
"""
from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

from pydantic import Field, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

PACKAGE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_DIR.parent.parent  # onoi/


def _find_env_file() -> str | None:
    explicit = os.environ.get("ONOI_ENV_FILE")
    if explicit:
        return explicit
    for candidate in (PROJECT_ROOT / ".env", Path.cwd() / ".env"):
        if candidate.exists():
            return str(candidate)
    return None


def _strip_inline_comment(value: object) -> object:
    """``KEY=value   # comment`` — systemd's EnvironmentFile keeps the comment as part of the value."""
    if not isinstance(value, str):
        return value
    text = value.strip()
    if text[:1] in ("'", '"'):
        return value
    head, sep, _ = text.partition(" #")
    if not sep:
        head, sep, _ = text.partition("\t#")
    return head.rstrip() if sep else value


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=_find_env_file(), env_file_encoding="utf-8", extra="ignore")

    @model_validator(mode="before")
    @classmethod
    def _clean_env_values(cls, data: object) -> object:
        if isinstance(data, dict):
            return {k: _strip_inline_comment(v) for k, v in data.items()}
        return data

    # --- runtime -----------------------------------------------------------
    app_env: str = Field(default="production", alias="APP_ENV")
    app_name: str = Field(default="OnoiPay", alias="APP_NAME")
    host: str = Field(default="127.0.0.1", alias="HOST")
    port: int = Field(default=7031, alias="PORT")
    public_url: str = Field(default="https://wwweeewww.fit", alias="PUBLIC_URL")
    base_path: str = Field(default="/onoipay", alias="BASE_PATH")
    timezone: str = Field(default="Asia/Bishkek", alias="TIMEZONE")
    log_level: str = Field(default="info", alias="LOG_LEVEL")
    data_dir: Path = Field(default=PROJECT_ROOT / "data", alias="DATA_DIR")
    frontend_dir: Path = Field(default=PROJECT_ROOT / "frontend" / "admin", alias="FRONTEND_DIR")
    trust_proxy: bool = Field(default=True, alias="TRUST_PROXY")

    # --- database ----------------------------------------------------------
    database_url: str = Field(default="sqlite:///./data/onoipay.sqlite3", alias="DATABASE_URL")
    db_pool_size: int = Field(default=10, alias="DB_POOL_SIZE")
    db_max_overflow: int = Field(default=20, alias="DB_MAX_OVERFLOW")

    # --- secrets (all required in production, generated by scripts/gen_secrets.py)
    secret_key: str = Field(default="", alias="SECRET_KEY")
    jwt_secret: str = Field(default="", alias="JWT_SECRET")
    session_secret: str = Field(default="", alias="SESSION_SECRET")
    webhook_secret: str = Field(default="", alias="WEBHOOK_SECRET")
    encryption_key: str = Field(default="", alias="ENCRYPTION_KEY")

    # --- admin auth ----------------------------------------------------------
    session_idle_days: int = Field(default=14, alias="SESSION_IDLE_DAYS")
    session_absolute_days: int = Field(default=60, alias="SESSION_ABSOLUTE_DAYS")
    access_token_minutes: int = Field(default=15, alias="ACCESS_TOKEN_MINUTES")
    login_max_attempts: int = Field(default=5, alias="LOGIN_MAX_ATTEMPTS")
    login_lock_minutes: int = Field(default=15, alias="LOGIN_LOCK_MINUTES")
    cookie_secure: bool = Field(default=True, alias="COOKIE_SECURE")

    # --- telegram -----------------------------------------------------------
    main_bot_token: str = Field(default="", alias="MAIN_BOT_TOKEN")
    main_bot_username: str = Field(default="OnoiPayBot", alias="MAIN_BOT_USERNAME")
    support_bot_token: str = Field(default="", alias="SUPPORT_BOT_TOKEN")
    support_bot_username: str = Field(default="OnoiHelpBot", alias="SUPPORT_BOT_USERNAME")
    admin_telegram_chat_ids: str = Field(default="", alias="ADMIN_TELEGRAM_CHAT_IDS")
    telegram_api_base: str = Field(default="https://api.telegram.org", alias="TELEGRAM_API_BASE")

    # --- email (Timeweb SMTP) -----------------------------------------------
    smtp_host: str = Field(default="", alias="SMTP_HOST")
    smtp_port: int = Field(default=465, alias="SMTP_PORT")
    smtp_ssl: bool = Field(default=True, alias="SMTP_SSL")
    smtp_starttls: bool = Field(default=False, alias="SMTP_STARTTLS")
    smtp_user: str = Field(default="", alias="SMTP_USER")
    smtp_password: str = Field(default="", alias="SMTP_PASSWORD")
    smtp_from: str = Field(default="", alias="SMTP_FROM")

    # --- optional IMAP payment source (bank e-mails) -------------------------
    imap_enabled: bool = Field(default=False, alias="IMAP_ENABLED")
    imap_host: str = Field(default="", alias="IMAP_HOST")
    imap_port: int = Field(default=993, alias="IMAP_PORT")
    imap_user: str = Field(default="", alias="IMAP_USER")
    imap_password: str = Field(default="", alias="IMAP_PASSWORD")
    imap_folder: str = Field(default="INBOX", alias="IMAP_FOLDER")
    imap_senders: str = Field(default="", alias="IMAP_SENDERS")
    imap_poll_seconds: float = Field(default=5.0, alias="IMAP_POLL_SECONDS")

    # --- web push ------------------------------------------------------------
    vapid_private_key: str = Field(default="", alias="VAPID_PRIVATE_KEY")
    vapid_public_key: str = Field(default="", alias="VAPID_PUBLIC_KEY")
    vapid_subject: str = Field(default="mailto:admin@wwweeewww.fit", alias="VAPID_SUBJECT")

    # --- workers ---------------------------------------------------------------
    worker_poll_seconds: float = Field(default=1.0, alias="WORKER_POLL_SECONDS")
    notification_max_age_seconds: int = Field(default=600, alias="NOTIFICATION_MAX_AGE_SECONDS")
    stuck_processing_timeout_seconds: int = Field(default=180, alias="STUCK_PROCESSING_TIMEOUT_SECONDS")

    @field_validator("base_path")
    @classmethod
    def _normalize_base_path(cls, value: str) -> str:
        value = (value or "").strip()
        if not value or value == "/":
            return ""
        return "/" + value.strip("/")

    @property
    def is_production(self) -> bool:
        return self.app_env.lower() in {"prod", "production"}

    @property
    def is_sqlite(self) -> bool:
        return self.database_url.startswith("sqlite")

    @property
    def admin_chat_ids(self) -> list[int]:
        out: list[int] = []
        for part in (self.admin_telegram_chat_ids or "").replace(";", ",").split(","):
            part = part.strip()
            if part.lstrip("-").isdigit():
                out.append(int(part))
        return out

    @property
    def imap_sender_list(self) -> list[str]:
        return [x.strip().lower() for x in (self.imap_senders or "").split(",") if x.strip()]

    def uploads_dir(self) -> Path:
        path = self.data_dir / "uploads"
        path.mkdir(parents=True, exist_ok=True)
        return path

    def require_secrets(self) -> list[str]:
        """Return names of missing secrets (used at startup in production)."""
        missing = []
        for name in ("secret_key", "jwt_secret", "session_secret", "webhook_secret", "encryption_key"):
            if len(getattr(self, name) or "") < 32:
                missing.append(name.upper())
        return missing


@lru_cache
def get_settings() -> Settings:
    settings = Settings()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    if settings.is_production:
        missing = settings.require_secrets()
        if missing:
            raise RuntimeError(
                "Missing or too short secrets: " + ", ".join(missing) + ". Run scripts/gen_secrets.py and fill .env"
            )
    return settings


def reset_settings_cache() -> None:
    get_settings.cache_clear()
