"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-04 20:53:08.700681+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_throttle',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bank_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('prefix', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('encode_payload', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('bot_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot', sa.String(length=16), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=48), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('panel_message_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot', 'telegram_id', name='uq_bot_sessions_bot_chat')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=False),
    sa.Column('last_error', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_run_at', ['status', 'run_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('bot', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('target_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_channel'), ['channel'], unique=False)
        batch_op.create_index('ix_notifications_channel_status_id', ['channel', 'status', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('payment_cashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('accepted_currency_ids', sa.String(length=200), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=False),
    sa.Column('deposit_enabled', sa.Boolean(), nullable=False),
    sa.Column('withdraw_enabled', sa.Boolean(), nullable=False),
    sa.Column('deposit_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deposit_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('withdraw_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('withdraw_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deposit_fee_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('withdraw_fee_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('auto_disable_enabled', sa.Boolean(), nullable=False),
    sa.Column('low_balance_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('critical_balance_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('auto_enable_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_daily_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('auto_disabled', sa.Boolean(), nullable=False),
    sa.Column('auto_disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_ok', sa.Boolean(), nullable=True),
    sa.Column('last_check_message', sa.String(length=400), nullable=False),
    sa.Column('instructions_text', sa.Text(), nullable=False),
    sa.Column('instruction_photo', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('event_key', sa.String(length=96), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=400), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_payment_events_status_received', ['status', 'received_at'], unique=False)

    op.create_table('support_rate_limits',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_text_hash', sa.String(length=64), nullable=False),
    sa.Column('last_text_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeats', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_escalation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_category'), ['category'], unique=False)
        batch_op.create_index('ix_system_logs_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_level'), ['level'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.String(length=300), nullable=False),
    sa.Column('support_blocked', sa.Boolean(), nullable=False),
    sa.Column('support_block_reason', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('referral_code', sa.String(length=24), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('referral_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referral_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deposits_count', sa.Integer(), nullable=False),
    sa.Column('withdrawals_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_referred_by', ['referred_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index('ux_users_email_nonempty', ['email'], unique=True, postgresql_where=sa.text("email <> '' AND email_verified_at IS NOT NULL"), sqlite_where=sa.text("email <> '' AND email_verified_at IS NOT NULL"))

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_created', ['created_at'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payment_requisites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bank_type', sa.String(length=32), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=128), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cash_id'], ['payment_cashes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_hash')
    )
    op.create_table('qr_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.String(length=300), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_records', schema=None) as batch_op:
        batch_op.create_index('ix_qr_records_user_last', ['user_id', 'last_used_at'], unique=False)

    op.create_table('saved_player_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=160), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cash_id'], ['payment_cashes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cash_id', 'player_id', name='uq_saved_player')
    )
    with op.batch_alter_table('saved_player_ids', schema=None) as batch_op:
        batch_op.create_index('ix_saved_player_user_cash', ['user_id', 'cash_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_admin_id'), ['admin_id'], unique=False)

    op.create_table('deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('requisite_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('payment_event_id', sa.Integer(), nullable=True),
    sa.Column('payment_source', sa.String(length=24), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=600), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('notified_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cash_id'], ['payment_cashes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisite_id'], ['payment_requisites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.create_index('ix_deposits_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_deposits_pay_amount_status', ['pay_amount', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposits_status'), ['status'], unique=False)
        batch_op.create_index('ix_deposits_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_deposits_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ux_deposits_active_pay_amount', ['pay_amount'], unique=True, postgresql_where=sa.text("status IN ('created','processing')"), sqlite_where=sa.text("status IN ('created','processing')"))

    op.create_table('push_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'subscription_id', name='uq_push_delivery')
    )
    with op.batch_alter_table('push_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_push_deliveries_status_next', ['status', 'next_attempt_at'], unique=False)

    op.create_table('referral_payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qr_record_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_record_id'], ['qr_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('provider_claim_key', sa.String(length=160), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=False),
    sa.Column('qr_record_id', sa.Integer(), nullable=True),
    sa.Column('qr_file_url', sa.Text(), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('generated_qr_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('deferred', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=600), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('notified_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cash_id'], ['payment_cashes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_record_id'], ['qr_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider_claim_key'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index('ix_withdrawals_cash_player_code', ['cash_id', 'player_id', 'code'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawals_status'), ['status'], unique=False)
        batch_op.create_index('ix_withdrawals_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_withdrawals_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('referral_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('invited_id', sa.Integer(), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reward', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposit_id')
    )
    op.create_table('support_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=True),
    sa.Column('withdrawal_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_user_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_conversations_status'), ['status'], unique=False)
        batch_op.create_index('ix_support_conversations_user_status', ['user_id', 'status'], unique=False)

    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('dedupe_key', sa.String(length=96), nullable=True),
    sa.Column('read_by_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index('ix_support_messages_conv_created', ['conversation_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_support_messages_conv_created')

    op.drop_table('support_messages')
    with op.batch_alter_table('support_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_support_conversations_user_status')
        batch_op.drop_index(batch_op.f('ix_support_conversations_status'))

    op.drop_table('support_conversations')
    op.drop_table('referral_rewards')
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index('ix_withdrawals_user_created')
        batch_op.drop_index('ix_withdrawals_status_created')
        batch_op.drop_index(batch_op.f('ix_withdrawals_status'))
        batch_op.drop_index('ix_withdrawals_cash_player_code')

    op.drop_table('withdrawals')
    op.drop_table('referral_payouts')
    with op.batch_alter_table('push_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_push_deliveries_status_next')

    op.drop_table('push_deliveries')
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_index('ux_deposits_active_pay_amount', postgresql_where=sa.text("status IN ('created','processing')"), sqlite_where=sa.text("status IN ('created','processing')"))
        batch_op.drop_index('ix_deposits_user_created')
        batch_op.drop_index('ix_deposits_status_created')
        batch_op.drop_index(batch_op.f('ix_deposits_status'))
        batch_op.drop_index('ix_deposits_pay_amount_status')
        batch_op.drop_index('ix_deposits_expires')

    op.drop_table('deposits')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_admin_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('saved_player_ids', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_player_user_cash')

    op.drop_table('saved_player_ids')
    with op.batch_alter_table('qr_records', schema=None) as batch_op:
        batch_op.drop_index('ix_qr_records_user_last')

    op.drop_table('qr_records')
    op.drop_table('push_subscriptions')
    op.drop_table('payment_requisites')
    op.drop_table('email_verifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ux_users_email_nonempty', postgresql_where=sa.text("email <> '' AND email_verified_at IS NOT NULL"), sqlite_where=sa.text("email <> '' AND email_verified_at IS NOT NULL"))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index('ix_users_referred_by')

    op.drop_table('users')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_level'))
        batch_op.drop_index('ix_system_logs_created')
        batch_op.drop_index(batch_op.f('ix_system_logs_category'))

    op.drop_table('system_logs')
    op.drop_table('support_rate_limits')
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_events_status_received')
        batch_op.drop_index(batch_op.f('ix_payment_events_status'))

    op.drop_table('payment_events')
    op.drop_table('payment_cashes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index('ix_notifications_channel_status_id')
        batch_op.drop_index(batch_op.f('ix_notifications_channel'))

    op.drop_table('notifications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_run_at')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    op.drop_table('bot_sessions')
    op.drop_table('bank_links')
    op.drop_table('auth_throttle')
    op.drop_table('admins')
    # ### end Alembic commands ###
