package kg.luxon.autopp;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private LinearLayout content; private final int neon=0xFF65FF3D, panel=0xFF0B100E, muted=0xFF9AA69F; private Switch bridge,openBank;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xFF050807);getWindow().setNavigationBarColor(0xFF050807);if(!Prefs.activated(this)){activationDialog();return;}startService(new Intent(this,AdminControlService.class));home();}
    private void activationDialog(){final EditText in=new EditText(this);in.setHint("API ключ");in.setTextColor(Color.WHITE);in.setHintTextColor(muted);in.setSingleLine();AlertDialog d=new AlertDialog.Builder(this).setTitle("Активация AutoPP").setView(in).setCancelable(false).setPositiveButton("Активировать",null).setNegativeButton("Закрыть",(q,w)->finish()).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String k=in.getText().toString().trim();if(k.isEmpty())return;Prefs.token(this,k);Executors.newSingleThreadExecutor().execute(()->{Http.Result r=AdminClient.heartbeat(this);runOnUiThread(()->{if(r.ok()){d.dismiss();startService(new Intent(this,AdminControlService.class));home();}else{Prefs.token(this,"");Toast.makeText(this,"Ключ не активирован: "+(r.error!=null?r.error:r.body),Toast.LENGTH_LONG).show();}});});}));d.show();}
    private void home(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(0xFF050807);MatrixView matrix=new MatrixView(this);root.addView(matrix,new FrameLayout.LayoutParams(-1,-1));ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(14),dp(18),dp(110));sv.addView(content);root.addView(sv,new FrameLayout.LayoutParams(-1,-1));setContentView(root);header();orb();permissions();openBankCard();bots();appsButton();}
    private void header(){LinearLayout r=row();ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.luxon_logo);r.addView(logo,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);txt.addView(text("AutoPP",26,Color.WHITE,true));txt.addView(text("Notification Bridge · v3.4.3",13,muted,false));r.addView(txt,new LinearLayout.LayoutParams(0,-2,1));TextView dot=text("●",22,neon,false);r.addView(dot);content.addView(r);}
    private void orb(){FrameLayout box=card();StatusOrbView o=new StatusOrbView(this);box.addView(o,new FrameLayout.LayoutParams(-1,dp(250)));LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER);c.setOrientation(LinearLayout.VERTICAL);c.addView(text("Система работает исправно",25,Color.WHITE,true));c.addView(text("LuxOn / Bingo независимые каналы",13,muted,false));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-2,Gravity.CENTER);box.addView(c,cp);content.addView(box,new LinearLayout.LayoutParams(-1,dp(270)));}
    private void permissions(){content.addView(title("Разрешения и состояние"));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackground(cardBg());c.addView(permission("Доступ к уведомлениям",AdminClient.notificationAccess(this),v->startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"))));c.addView(permission("Батарея без ограничений",AdminClient.batteryUnrestricted(this),v->{Intent i=new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, Uri.parse("package:"+getPackageName()));startActivity(i);}));c.addView(permission("Поверх других приложений",Build.VERSION.SDK_INT<23||Settings.canDrawOverlays(this),v->{startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));}));c.addView(permission("Геолокация",checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED,v->requestLocation()));content.addView(c);}
    private void openBankCard(){content.addView(title("Открытый банк"));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackground(cardBg());LinearLayout r=row();r.addView(text("Плавающая панель",18,Color.WHITE,true),new LinearLayout.LayoutParams(0,-2,1));openBank=new Switch(this);openBank.setChecked(Prefs.openBank(this));r.addView(openBank);c.addView(r);Button overlay=button("Показать панель");overlay.setOnClickListener(v->startOverlay());c.addView(overlay);Button access=button("Спец. возможности");access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));c.addView(access);openBank.setOnCheckedChangeListener((b,on)->{Prefs.openBank(this,on);tone(on);if(on)startOverlay();});content.addView(c);}
    private void bots(){content.addView(title("Боты"));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackground(cardBg());Switch l=new Switch(this);l.setText("LuxOn");l.setTextColor(Color.WHITE);l.setChecked(Prefs.luxonEnabled(this));l.setOnCheckedChangeListener((b,v)->Prefs.luxonEnabled(this,v));c.addView(l);Switch bi=new Switch(this);bi.setText("Bingo");bi.setTextColor(Color.WHITE);bi.setChecked(Prefs.bingoEnabled(this));bi.setOnCheckedChangeListener((b,v)->Prefs.bingoEnabled(this,v));c.addView(bi);Button cfg=button("Адреса / PIN");cfg.setOnClickListener(v->pinDialog());c.addView(cfg);content.addView(c);}
    private void appsButton(){Button b=button("Выбрать приложения");b.setOnClickListener(v->showApps());content.addView(b);}
    private void showApps(){final Dialog d=new Dialog(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));root.setBackgroundColor(0xFF050807);root.addView(title("Выбор приложений"));EditText q=new EditText(this);q.setHint("Поиск по названию или пакету");q.setTextColor(Color.WHITE);q.setHintTextColor(muted);root.addView(q,new LinearLayout.LayoutParams(-1,dp(54)));ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Set<String> selected=Prefs.selectedPackages(this);List<PackageInfo> pkgs=getPackageManager().getInstalledPackages(0);Runnable render=()->{list.removeAllViews();String s=q.getText().toString().toLowerCase(Locale.ROOT);int shown=0;for(PackageInfo pi:pkgs){ApplicationInfo ai=pi.applicationInfo;if(ai==null)continue;String name=getPackageManager().getApplicationLabel(ai).toString();if(!s.isEmpty()&&!name.toLowerCase(Locale.ROOT).contains(s)&&!pi.packageName.toLowerCase(Locale.ROOT).contains(s))continue;CheckBox cb=new CheckBox(this);cb.setText(name+"\n"+pi.packageName);cb.setTextColor(Color.WHITE);cb.setChecked(selected.contains(pi.packageName));cb.setPadding(dp(4),dp(8),dp(4),dp(8));cb.setOnCheckedChangeListener((b,v)->{if(v)selected.add(pi.packageName);else selected.remove(pi.packageName);});list.addView(cb,new LinearLayout.LayoutParams(-1,-2));shown++;}};q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){render.run();}public void afterTextChanged(android.text.Editable e){}});render.run();Button save=button("Сохранить");save.setOnClickListener(v->{Prefs.selectedPackages(this,selected);d.dismiss();});root.addView(save);d.setContentView(root);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94f),(int)(getResources().getDisplayMetrics().heightPixels*.94f));}d.show();}
    private void pinDialog(){final EditText pin=new EditText(this);pin.setInputType(2);new AlertDialog.Builder(this).setTitle("PIN").setView(pin).setPositiveButton("Открыть",(d,w)->{if("972936".equals(pin.getText().toString()))endpointDialog();else Toast.makeText(this,"Неверный PIN",Toast.LENGTH_SHORT).show();}).setNegativeButton("Отмена",null).show();}
    private void endpointDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=new EditText(this);a.setText(Prefs.luxonEndpoint(this));EditText b=new EditText(this);b.setText(Prefs.bingoEndpoint(this));l.addView(a);l.addView(b);new AlertDialog.Builder(this).setTitle("Адреса ботов").setView(l).setPositiveButton("Сохранить",(d,w)->{Prefs.luxonEndpoint(this,a.getText().toString());Prefs.bingoEndpoint(this,b.getText().toString());}).show();}
    private void requestLocation(){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},70);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==70&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){Prefs.locationConsent(this,true);if(Build.VERSION.SDK_INT>=26)startForegroundService(new Intent(this,LocationReporterService.class));else startService(new Intent(this,LocationReporterService.class));home();}}
    private void startOverlay(){if(Build.VERSION.SDK_INT>=23&&!Settings.canDrawOverlays(this)){startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));return;}if(Build.VERSION.SDK_INT>=26)startForegroundService(new Intent(this,OverlayService.class));else startService(new Intent(this,OverlayService.class));}
    private void tone(boolean on){new android.media.ToneGenerator(android.media.AudioManager.STREAM_NOTIFICATION,60).startTone(on?android.media.ToneGenerator.TONE_PROP_ACK:android.media.ToneGenerator.TONE_PROP_NACK,120);}
    private LinearLayout permission(String name,boolean ok,View.OnClickListener click){LinearLayout r=row();TextView t=text(name,16,Color.WHITE,true);r.addView(t,new LinearLayout.LayoutParams(0,dp(54),1));TextView s=text(ok?"●":"○",26,ok?neon:0xFFFF5C5C,false);s.setGravity(Gravity.CENTER);r.addView(s,new LinearLayout.LayoutParams(dp(54),dp(54)));r.setOnClickListener(click);return r;}
    private TextView title(String s){TextView t=text(s,22,Color.WHITE,true);t.setPadding(0,dp(22),0,dp(10));return t;} private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;} private FrameLayout card(){FrameLayout f=new FrameLayout(this);f.setBackground(cardBg());return f;} private GradientDrawable cardBg(){GradientDrawable g=new GradientDrawable();g.setColor(panel);g.setCornerRadius(dp(20));g.setStroke(dp(1),0xFF314238);return g;} private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);t.setPadding(dp(8),dp(4),dp(8),dp(4));return t;} private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.BLACK);GradientDrawable g=new GradientDrawable();g.setColor(neon);g.setCornerRadius(dp(16));b.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(8),0,dp(8));b.setLayoutParams(p);return b;} private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
}
