"""Application configuration.

Every secret and environment-specific value comes from environment variables
(or a .env file next to the project root). Nothing sensitive is stored in the
source tree or in the database in plain text.
"""
from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path
from typing import Any

from pydantic import Field, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

PACKAGE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_DIR.parent.parent  # paygo/


def _find_env_file() -> str | None:
    explicit = os.environ.get("PAYGO_ENV_FILE")
    if explicit:
        return explicit
    for candidate in (PROJECT_ROOT / ".env", Path.cwd() / ".env"):
        if candidate.exists():
            return str(candidate)
    return None


def _strip_inline_comment(value: object) -> object:
    """``KEY=value   # comment`` — systemd's EnvironmentFile keeps the comment as part of the value."""
    if not isinstance(value, str):
        return value
    text = value.strip()
    if text[:1] in ("'", '"'):
        return value
    head, sep, _ = text.partition(" #")
    if not sep:
        head, sep, _ = text.partition("\t#")
    return head.rstrip() if sep else value


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=_find_env_file(), env_file_encoding="utf-8", extra="ignore")

    @model_validator(mode="before")
    @classmethod
    def _clean_env_values(cls, data: object) -> object:
        if isinstance(data, dict):
            return {k: _strip_inline_comment(v) for k, v in data.items()}
        return data

    # --- runtime -----------------------------------------------------------
    app_env: str = Field(default="production", alias="APP_ENV")
    app_name: str = Field(default="PayGo", alias="APP_NAME")
    host: str = Field(default="127.0.0.1", alias="HOST")
    port: int = Field(default=7035, alias="PORT")
    public_url: str = Field(default="https://wwweeewww.fit", alias="PUBLIC_URL")
    base_path: str = Field(default="/paygo", alias="BASE_PATH")
    timezone: str = Field(default="Asia/Bishkek", alias="TIMEZONE")
    log_level: str = Field(default="info", alias="LOG_LEVEL")
    data_dir: Path = Field(default=PROJECT_ROOT / "data", alias="DATA_DIR")
    frontend_dir: Path = Field(default=PROJECT_ROOT / "frontend" / "admin", alias="FRONTEND_DIR")
    trust_proxy: bool = Field(default=True, alias="TRUST_PROXY")
    # optional: only these IPs/CIDRs may use the admin panel and API (empty = no restriction)
    admin_ip_allowlist: str = Field(default="", alias="ADMIN_IP_ALLOWLIST")

    # --- database ----------------------------------------------------------
    database_url: str = Field(default="sqlite:///./data/paygo.sqlite3", alias="DATABASE_URL")
    db_pool_size: int = Field(default=10, alias="DB_POOL_SIZE")
    db_max_overflow: int = Field(default=20, alias="DB_MAX_OVERFLOW")

    # --- secrets (all required in production, generated by scripts/gen_secrets.py)
    secret_key: str = Field(default="", alias="SECRET_KEY")
    jwt_secret: str = Field(default="", alias="JWT_SECRET")
    session_secret: str = Field(default="", alias="SESSION_SECRET")
    webhook_secret: str = Field(default="", alias="WEBHOOK_SECRET")
    encryption_key: str = Field(default="", alias="ENCRYPTION_KEY")

    # --- admin auth ----------------------------------------------------------
    session_idle_days: int = Field(default=14, alias="SESSION_IDLE_DAYS")
    session_absolute_days: int = Field(default=60, alias="SESSION_ABSOLUTE_DAYS")
    access_token_minutes: int = Field(default=15, alias="ACCESS_TOKEN_MINUTES")
    login_max_attempts: int = Field(default=5, alias="LOGIN_MAX_ATTEMPTS")
    login_lock_minutes: int = Field(default=15, alias="LOGIN_LOCK_MINUTES")
    cookie_secure: bool = Field(default=True, alias="COOKIE_SECURE")

    # --- telegram -----------------------------------------------------------
    main_bot_token: str = Field(default="", alias="MAIN_BOT_TOKEN")
    main_bot_username: str = Field(default="PayGoXBot", alias="MAIN_BOT_USERNAME")
    support_bot_token: str = Field(default="", alias="SUPPORT_BOT_TOKEN")
    support_bot_username: str = Field(default="PayOperator_bot", alias="SUPPORT_BOT_USERNAME")
    admin_telegram_chat_ids: str = Field(default="", alias="ADMIN_TELEGRAM_CHAT_IDS")
    telegram_api_base: str = Field(default="https://api.telegram.org", alias="TELEGRAM_API_BASE")

    # --- email (Timeweb SMTP) -----------------------------------------------
    smtp_host: str = Field(default="", alias="SMTP_HOST")
    smtp_port: int = Field(default=465, alias="SMTP_PORT")
    smtp_ssl: bool = Field(default=True, alias="SMTP_SSL")
    smtp_starttls: bool = Field(default=False, alias="SMTP_STARTTLS")
    smtp_user: str = Field(default="", alias="SMTP_USER")
    smtp_password: str = Field(default="", alias="SMTP_PASSWORD")
    smtp_from: str = Field(default="", alias="SMTP_FROM")

    # --- Claude support assistant (key only from the environment) ---------------
    anthropic_api_key: str = Field(default="", alias="ANTHROPIC_API_KEY")
    assistant_model: str = Field(default="claude-opus-5", alias="ASSISTANT_MODEL")
    # --- panel login confirmed in the main bot by this Telegram account -----------
    login_approver_telegram_id: int = Field(default=8274883903, alias="LOGIN_APPROVER_TELEGRAM_ID")
    login_session_days: int = Field(default=30, alias="LOGIN_SESSION_DAYS")
    login_request_ttl_seconds: int = Field(default=180, alias="LOGIN_REQUEST_TTL_SECONDS")

    # --- optional IMAP payment source (bank e-mails) -------------------------
    imap_enabled: bool = Field(default=False, alias="IMAP_ENABLED")
    imap_host: str = Field(default="", alias="IMAP_HOST")
    imap_port: int = Field(default=993, alias="IMAP_PORT")
    imap_user: str = Field(default="", alias="IMAP_USER")
    imap_password: str = Field(default="", alias="IMAP_PASSWORD")
    imap_folder: str = Field(default="INBOX", alias="IMAP_FOLDER")
    imap_senders: str = Field(default="", alias="IMAP_SENDERS")
    imap_poll_seconds: float = Field(default=5.0, alias="IMAP_POLL_SECONDS")
    # push mode (IMAP IDLE): mail is processed the moment it arrives; false = poll every IMAP_POLL_SECONDS
    imap_idle: bool = Field(default=True, alias="IMAP_IDLE")

    # --- web push ------------------------------------------------------------
    vapid_private_key: str = Field(default="", alias="VAPID_PRIVATE_KEY")
    vapid_public_key: str = Field(default="", alias="VAPID_PUBLIC_KEY")
    vapid_subject: str = Field(default="mailto:admin@wwweeewww.fit", alias="VAPID_SUBJECT")

    # --- workers ---------------------------------------------------------------
    worker_poll_seconds: float = Field(default=1.0, alias="WORKER_POLL_SECONDS")
    notification_max_age_seconds: int = Field(default=600, alias="NOTIFICATION_MAX_AGE_SECONDS")
    stuck_processing_timeout_seconds: int = Field(default=180, alias="STUCK_PROCESSING_TIMEOUT_SECONDS")

    # --- automatic payouts (client withdrawals sent from an owner banking account) ---
    # Which payout channel the auto-withdrawal engine uses. "" disables it entirely,
    # "optima24" drives the Optima24 mobile-bank API, "fake" is a no-network simulator
    # used by tests and by a first dry run. Secrets live ONLY here / in .env — never in
    # the database, the source tree, or a delivered archive. The admin-panel switches
    # (autopay_enabled, autopay_dry_run, limits) control behaviour, not these values.
    payout_provider: str = Field(default="", alias="PAYOUT_PROVIDER")
    optima24_base_url: str = Field(default="https://telebank3.optima24.kg:3080", alias="OPTIMA24_BASE_URL")
    optima24_login: str = Field(default="", alias="OPTIMA24_LOGIN")
    optima24_password: str = Field(default="", alias="OPTIMA24_PASSWORD")
    optima24_device_id: str = Field(default="", alias="OPTIMA24_DEVICE_ID")
    optima24_device_token: str = Field(default="", alias="OPTIMA24_DEVICE_TOKEN")
    optima24_source_account: str = Field(default="", alias="OPTIMA24_SOURCE_ACCOUNT")
    # the mobile app itself waits 30s per call, so the client mirrors that ceiling
    optima24_timeout_seconds: float = Field(default=30.0, alias="OPTIMA24_TIMEOUT_SECONDS")
    # telebank3 serves a self-signed certificate (the app trusts a pinned cert). Point
    # OPTIMA24_CA_BUNDLE at a saved copy of that cert chain to verify against it (secure,
    # recommended). Only if that is impractical, set OPTIMA24_TLS_VERIFY=false to skip
    # verification — the connection still encrypts, but no longer proves it is really Optima.
    optima24_ca_bundle: str = Field(default="", alias="OPTIMA24_CA_BUNDLE")
    optima24_tls_verify: bool = Field(default=True, alias="OPTIMA24_TLS_VERIFY")
    # Several Optima24 accounts (several phones): a JSON list, each entry an object with
    # login/password and optionally name/device_id/device_token/source_account/base_url.
    # Missing fields fall back to the single OPTIMA24_* values above. Empty = use just the
    # single account from the flat OPTIMA24_* variables. Codes for every account may share
    # one OTP mailbox, because payouts are sent one at a time.
    optima24_accounts: str = Field(default="", alias="OPTIMA24_ACCOUNTS")
    # Optima confirms each transfer with a one-time code sent to e-mail. A dedicated mailbox
    # receives only these codes; PayGo reads it over IMAP and confirms the transfer itself —
    # no phone needed. Keep it SEPARATE from the deposit IMAP mailbox so the two never clash.
    optima_otp_imap_host: str = Field(default="", alias="OPTIMA_OTP_IMAP_HOST")
    optima_otp_imap_port: int = Field(default=993, alias="OPTIMA_OTP_IMAP_PORT")
    optima_otp_imap_user: str = Field(default="", alias="OPTIMA_OTP_IMAP_USER")
    optima_otp_imap_password: str = Field(default="", alias="OPTIMA_OTP_IMAP_PASSWORD")
    optima_otp_imap_folder: str = Field(default="INBOX", alias="OPTIMA_OTP_IMAP_FOLDER")
    # only mail from this sender is trusted as a code source (substring match, e.g. optima24.kg)
    optima_otp_sender: str = Field(default="", alias="OPTIMA_OTP_SENDER")
    # optional subject filter (substring); empty = any subject from the trusted sender
    optima_otp_subject: str = Field(default="", alias="OPTIMA_OTP_SUBJECT")
    # regex whose first group is the code; the default takes the first 4-8 digit run
    optima_otp_code_regex: str = Field(default=r"(\d{4,8})", alias="OPTIMA_OTP_CODE_REGEX")
    optima_otp_wait_seconds: float = Field(default=90.0, alias="OPTIMA_OTP_WAIT_SECONDS")
    optima_otp_poll_seconds: float = Field(default=3.0, alias="OPTIMA_OTP_POLL_SECONDS")

    @field_validator("base_path")
    @classmethod
    def _normalize_base_path(cls, value: str) -> str:
        value = (value or "").strip()
        if not value or value == "/":
            return ""
        return "/" + value.strip("/")

    @property
    def is_production(self) -> bool:
        return self.app_env.lower() in {"prod", "production"}

    @property
    def is_sqlite(self) -> bool:
        return self.database_url.startswith("sqlite")

    @property
    def admin_chat_ids(self) -> list[int]:
        out: list[int] = []
        for part in (self.admin_telegram_chat_ids or "").replace(";", ",").split(","):
            part = part.strip()
            if part.lstrip("-").isdigit():
                out.append(int(part))
        return out

    @property
    def imap_sender_list(self) -> list[str]:
        return [x.strip().lower() for x in (self.imap_senders or "").split(",") if x.strip()]

    @property
    def payout_provider_name(self) -> str:
        return (self.payout_provider or "").strip().lower()

    @property
    def optima24_account_list(self) -> list[dict[str, Any]]:
        """Resolved Optima24 accounts: the JSON list, or a single account from the flat vars.

        Every entry is filled in from the flat OPTIMA24_* values where a field is missing, so
        a shared base URL / device only needs to be set once. Accounts without login+password
        are dropped.
        """
        import json

        raw = (self.optima24_accounts or "").strip()
        entries: list[dict[str, Any]] = []
        if raw:
            try:
                data = json.loads(raw)
                if isinstance(data, list):
                    entries = [a for a in data if isinstance(a, dict)]
            except Exception:
                entries = []
        if not entries:
            entries = [{}]  # single account from the flat OPTIMA24_* variables
        out: list[dict[str, Any]] = []
        for i, a in enumerate(entries):
            resolved = {
                "name": str(a.get("name") or f"optima{i + 1}"),
                "base_url": a.get("base_url") or self.optima24_base_url,
                "login": a.get("login") or self.optima24_login,
                "password": a.get("password") or self.optima24_password,
                "device_id": a.get("device_id") or self.optima24_device_id,
                "device_token": a.get("device_token") or self.optima24_device_token,
                "source_account": a.get("source_account") or self.optima24_source_account,
                "timeout": self.optima24_timeout_seconds,
            }
            if resolved["login"] and resolved["password"]:
                out.append(resolved)
        return out

    @property
    def payout_configured(self) -> bool:
        """A payout channel is selected and its required secrets are present."""
        name = self.payout_provider_name
        if name == "fake":
            return True
        if name == "optima24":
            return bool(self.optima24_account_list)
        return False

    def uploads_dir(self) -> Path:
        path = self.data_dir / "uploads"
        path.mkdir(parents=True, exist_ok=True)
        return path

    def require_secrets(self) -> list[str]:
        """Return names of missing secrets (used at startup in production)."""
        missing = []
        for name in ("secret_key", "jwt_secret", "session_secret", "webhook_secret", "encryption_key"):
            if len(getattr(self, name) or "") < 32:
                missing.append(name.upper())
        return missing


@lru_cache
def get_settings() -> Settings:
    settings = Settings()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    if settings.is_production:
        missing = settings.require_secrets()
        if missing:
            raise RuntimeError(
                "Missing or too short secrets: " + ", ".join(missing) + ". Run scripts/gen_secrets.py and fill .env"
            )
    return settings


def reset_settings_cache() -> None:
    get_settings.cache_clear()
